### ISSUE TITLE
OpenEXR fails

### ISSUE THREAD

**Issue by wingz1** [limbo-ml/user#2]
Can't pip install.   Fails on the OpenEXR install.  Any ideas?

**Comment by tshead2** [comment]
Unfortunately, the OpenEXR package on PyPI contains just the Python bindings - it can't be built without the OpenEXR library and header files.  If you use conda as your Python distribution (something I strongly recommend, BTW), you can install all the above with a single command:

```$ conda install openexr-python```

I will update the documentation to clarify this.

Cheers,
Tim

**Comment by tshead2** [comment]
The documentation at

     https://limbo-ml.readthedocs.io/en/latest/installation.html

now correctly reflects this.  Many thanks for pointing out the problem, and don't hesitate to report any further issues.

Cheers,
Tim
